In [2]:
import pandas as pd 

df = pd.read_csv("../data/raw/global_placement.csv")
df.tail()

,cgpa,backlogs,college_tier,country,university_ranking_band,internship_count,aptitude_score,communication_score,specialization,industry,internship_quality_score,placement_status,salary
9995,8.040882,0,Tier 3,USA,100-300,2,98.120449,80.866213,Data Science,Manufacturing,6.298524,Placed,109831.584346
9996,5.401324,3,Tier 1,UK,100-300,1,68.622854,83.458035,Data Science,Consulting,7.352717,Not Placed,0.000000
9997,6.435747,0,Tier 3,UK,300+,2,69.067773,50.992745,Core CS,Other,3.871205,Placed,69818.819355
9998,7.396612,1,Tier 3,Germany,100-300,3,45.050463,86.807882,Cloud,Finance,3.687731,Placed,82797.577423
9999,7.515511,3,Tier 2,UK,300+,4,66.947232,46.385843,AI/ML,Manufacturing,4.181389,Placed,105387.859101

In [5]:
df.isnull().sum()

cgpa                        0
backlogs                    0
college_tier                0
country                     0
university_ranking_band     0
internship_count            0
aptitude_score              0
communication_score         0
specialization              0
industry                    0
internship_quality_score    0
placement_status            0
salary                      0
dtype: int64

In [3]:
df2 = pd.read_csv("../data/processed/X_train_cls.csv")
df2.head()

,cgpa,backlogs,college_tier,university_ranking_band,internship_count,aptitude_score,communication_score,internship_quality_score,total_internship_value,academic_power,...,country_USA,specialization_Cloud,specialization_Core CS,specialization_Cybersecurity,specialization_Data Science,industry_Finance,industry_Healthcare,industry_Manufacturing,industry_Other,industry_Tech
0,0.215717,1,3,2,-0.404427,-0.850073,-0.702633,-0.994597,-0.589683,0.330592,...,False,False,False,True,False,False,False,True,False,False
1,-0.747108,1,3,3,-0.404427,-0.027760,0.627973,-1.228953,-0.642129,1.220515,...,False,False,False,False,True,False,True,False,False,False
2,-0.240648,1,2,1,1.258598,-1.194665,-0.049248,1.393862,2.064684,-1.051461,...,False,False,True,False,False,True,False,False,False,False
3,-1.544833,2,2,2,-0.404427,0.933572,0.100704,-0.392425,-0.454925,-0.187471,...,False,True,False,False,False,False,False,False,False,True
4,0.697575,1,1,3,-1.235939,0.231974,1.525162,-0.224444,-1.115107,1.858189,...,True,False,True,False,False,False,False,False,False,False

In [4]:
df2 = pd.read_csv("../data/processed/X_train_reg.csv")
df2.head()

,cgpa,backlogs,college_tier,university_ranking_band,internship_count,aptitude_score,communication_score,internship_quality_score,total_internship_value,academic_power,...,country_USA,specialization_Cloud,specialization_Core CS,specialization_Cybersecurity,specialization_Data Science,industry_Finance,industry_Healthcare,industry_Manufacturing,industry_Other,industry_Tech
0,1.065830,2,3,2,0.249300,-0.105787,1.137483,-1.020578,-0.183484,0.451802,...,False,False,True,False,False,False,False,False,True,False
1,1.343270,2,1,2,0.249300,-0.444688,-1.759029,0.823792,0.575525,0.526379,...,False,False,False,False,True,False,True,False,False,False
2,0.963315,1,3,1,-1.354691,0.269277,0.210508,1.379742,-1.232738,-0.996872,...,True,True,False,False,False,False,False,True,False,False
3,1.385722,0,2,3,1.853291,0.985752,2.276896,-0.478743,1.311730,2.015681,...,True,False,False,False,False,False,False,False,False,False
4,-1.099038,1,1,2,-0.552696,-0.268635,0.686170,1.429784,-0.203915,-0.130124,...,True,True,False,False,False,False,False,False,True,False